#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SoftTelekom.Android.Resource", IsApplication=true)]

namespace SoftTelekom.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::SoftTelekom.Android.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::SoftTelekom.Android.Resource.String.Hello;
			global::EShyMedia.MvvmCross.Plugins.Settings.Droid.Resource.String.ApplicationName = global::SoftTelekom.Android.Resource.String.ApplicationName;
			global::EShyMedia.MvvmCross.Plugins.Settings.Droid.Resource.String.Hello = global::SoftTelekom.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000a
			public const int bgcolor = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int darkblue = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int darkgray = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int gold = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int lightblue = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int lightgray = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int menucolor = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int menuselectedcolor = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int test = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int titlecolor = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int transparent = 2131034121;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060011
			public const int button_padding = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int button_radius = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int defaultPadding = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int defaultPadding_2x = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int defaultPadding_3x = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int defaultPadding_4x = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int defaultPadding_5x = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int defaultPadding_6x = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int extra_large_font = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int keyboard_font_size = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int large_font = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int list_padding = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int llarge_font = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int normal_font = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int shadow_width = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int slidingmenu_offset = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int small_font = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int very_small_font = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_state_pressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_state_transparent = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edittext_standard = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Info = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int MenuBg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int MenuBlueBg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int shadow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int splash = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int MvxBindingTagUnique = 2131230720;
			
			// aapt resource value: 0x7f080017
			public const int addTrans_mainCategoryList = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int button_gps = 2131230742;
			
			// aapt resource value: 0x7f08000a
			public const int button_send = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int custom_toast_layout_id = 2131230734;
			
			// aapt resource value: 0x7f080012
			public const int fragmentHost = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int imageView1 = 2131230735;
			
			// aapt resource value: 0x7f080004
			public const int linearLayout1 = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout2 = 2131230721;
			
			// aapt resource value: 0x7f080014
			public const int menu_frame = 2131230740;
			
			// aapt resource value: 0x7f080003
			public const int scrollView1 = 2131230723;
			
			// aapt resource value: 0x7f080013
			public const int slidingmenu = 2131230739;
			
			// aapt resource value: 0x7f080002
			public const int textView1 = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int textView2 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int textView3 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int textView4 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int textView5 = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int textView6 = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int textView7 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int textView8 = 2131230733;
			
			// aapt resource value: 0x7f08000b
			public const int textView_paid = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int textview_title = 2131230741;
			
			// aapt resource value: 0x7f080011
			public const int toastMessageTextView = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int toastTitleTextView = 2131230736;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int num_cols = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdministrationView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BillingInfo_ListElement = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BillingInfoView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int City_DropDownItemTemplate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int City_ItemTemplate = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ContactView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CustomToast = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DashboardView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int enum_dropdownitemtemplate = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int enum_item_tamplet = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int InternetUsageView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int InternetUseage_ListElement = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Menu_Fragment = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int menu_frame = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Menu_ListElement = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int News_ListElement = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int NewsView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int OrderView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ReportView = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SettingsView = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Speed_DropDownItemTemplate = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Speed_ItemTemplate = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int SplashScreen = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int UserInfoView = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int WebmailView = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int close_drawer = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int open_drawer = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090005
			public const int ButtonStyle_standard = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int EditTextStyle_standard = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int EditTextStyle_standard_multiline = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int MainLayoutBackground_Dashboard = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int TextViewStyle = 2131296257;
			
			// aapt resource value: 0x7f09000a
			public const int TextViewStyle_contact = 2131296266;
			
			// aapt resource value: 0x7f090006
			public const int TextViewStyle_standard_black_18 = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int TextViewStyle_title_black_22 = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int TextViewStyle_title_black_24 = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int TextViewStyle_title_white_22 = 2131296263;
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
