#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SoftTelekom.Android.Resource", IsApplication=true)]

namespace SoftTelekom.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::SoftTelekom.Android.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::SoftTelekom.Android.Resource.String.Hello;
			global::EShyMedia.MvvmCross.Plugins.Settings.Droid.Resource.String.ApplicationName = global::SoftTelekom.Android.Resource.String.ApplicationName;
			global::EShyMedia.MvvmCross.Plugins.Settings.Droid.Resource.String.Hello = global::SoftTelekom.Android.Resource.String.Hello;
			global::SlidingMenuSharp.Resource.Attribute.behindOffset = global::SoftTelekom.Android.Resource.Attribute.behindOffset;
			global::SlidingMenuSharp.Resource.Attribute.behindScrollScale = global::SoftTelekom.Android.Resource.Attribute.behindScrollScale;
			global::SlidingMenuSharp.Resource.Attribute.behindWidth = global::SoftTelekom.Android.Resource.Attribute.behindWidth;
			global::SlidingMenuSharp.Resource.Attribute.fadeDegree = global::SoftTelekom.Android.Resource.Attribute.fadeDegree;
			global::SlidingMenuSharp.Resource.Attribute.fadeEnabled = global::SoftTelekom.Android.Resource.Attribute.fadeEnabled;
			global::SlidingMenuSharp.Resource.Attribute.mode = global::SoftTelekom.Android.Resource.Attribute.mode;
			global::SlidingMenuSharp.Resource.Attribute.selectorDrawable = global::SoftTelekom.Android.Resource.Attribute.selectorDrawable;
			global::SlidingMenuSharp.Resource.Attribute.selectorEnabled = global::SoftTelekom.Android.Resource.Attribute.selectorEnabled;
			global::SlidingMenuSharp.Resource.Attribute.shadowDrawable = global::SoftTelekom.Android.Resource.Attribute.shadowDrawable;
			global::SlidingMenuSharp.Resource.Attribute.shadowWidth = global::SoftTelekom.Android.Resource.Attribute.shadowWidth;
			global::SlidingMenuSharp.Resource.Attribute.touchModeAbove = global::SoftTelekom.Android.Resource.Attribute.touchModeAbove;
			global::SlidingMenuSharp.Resource.Attribute.touchModeBehind = global::SoftTelekom.Android.Resource.Attribute.touchModeBehind;
			global::SlidingMenuSharp.Resource.Attribute.viewAbove = global::SoftTelekom.Android.Resource.Attribute.viewAbove;
			global::SlidingMenuSharp.Resource.Attribute.viewBehind = global::SoftTelekom.Android.Resource.Attribute.viewBehind;
			global::SlidingMenuSharp.Resource.Id.fullscreen = global::SoftTelekom.Android.Resource.Id.fullscreen;
			global::SlidingMenuSharp.Resource.Id.left = global::SoftTelekom.Android.Resource.Id.left;
			global::SlidingMenuSharp.Resource.Id.margin = global::SoftTelekom.Android.Resource.Id.margin;
			global::SlidingMenuSharp.Resource.Id.right = global::SoftTelekom.Android.Resource.Id.right;
			global::SlidingMenuSharp.Resource.Id.selected_view = global::SoftTelekom.Android.Resource.Id.selected_view;
			global::SlidingMenuSharp.Resource.Id.slidingmenumain = global::SoftTelekom.Android.Resource.Id.slidingmenumain;
			global::SlidingMenuSharp.Resource.Layout.slidingmenumain = global::SoftTelekom.Android.Resource.Layout.slidingmenumain;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindOffset = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_behindOffset;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindScrollScale = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_behindScrollScale;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindWidth = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_behindWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeDegree = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_fadeDegree;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeEnabled = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_fadeEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_mode = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_mode;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorDrawable = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_selectorDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorEnabled = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_selectorEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowDrawable = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_shadowDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowWidth = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_shadowWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeAbove = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_touchModeAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeBehind = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_touchModeBehind;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewAbove = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_viewAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewBehind = global::SoftTelekom.Android.Resource.Styleable.SlidingMenu_viewBehind;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000e
			public const int MvxBind = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int MvxDropDownItemTemplate = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int MvxItemTemplate = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public const int MvxLang = 2130771983;
			
			// aapt resource value: 0x7f010013
			public const int MvxSource = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int MvxTemplate = 2130771984;
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000a
			public const int bgcolor = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int darkblue = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int darkgray = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int gold = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int lightblue = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int lightgray = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int menucolor = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int menuselectedcolor = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int test = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int titlecolor = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int transparent = 2131099657;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070011
			public const int button_padding = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int button_radius = 2131165200;
			
			// aapt resource value: 0x7f07000a
			public const int defaultPadding = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int defaultPadding_2x = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int defaultPadding_3x = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int defaultPadding_4x = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int defaultPadding_5x = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int defaultPadding_6x = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int extra_large_font = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int keyboard_font_size = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int large_font = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int list_padding = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int llarge_font = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int normal_font = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int shadow_width = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int slidingmenu_offset = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int small_font = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int very_small_font = 2131165187;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_state_pressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_state_transparent = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edittext_standard = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Info = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int MenuBg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int shadow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int MvxBindingTagUnique = 2130968581;
			
			// aapt resource value: 0x7f04001c
			public const int addTrans_mainCategoryList = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int button_gps = 2130968603;
			
			// aapt resource value: 0x7f04000f
			public const int button_send = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int custom_toast_layout_id = 2130968595;
			
			// aapt resource value: 0x7f040017
			public const int fragmentHost = 2130968599;
			
			// aapt resource value: 0x7f040003
			public const int fullscreen = 2130968579;
			
			// aapt resource value: 0x7f040014
			public const int imageView1 = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int left = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int linearLayout1 = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int linearLayout2 = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int margin = 2130968578;
			
			// aapt resource value: 0x7f040019
			public const int menu_frame = 2130968601;
			
			// aapt resource value: 0x7f040001
			public const int right = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int scrollView1 = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int selected_view = 2130968580;
			
			// aapt resource value: 0x7f040018
			public const int slidingmenu = 2130968600;
			
			// aapt resource value: 0x7f04001d
			public const int slidingmenumain = 2130968605;
			
			// aapt resource value: 0x7f040007
			public const int textView1 = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int textView2 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int textView3 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int textView4 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int textView5 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int textView6 = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int textView7 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int textView8 = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int textView_paid = 2130968592;
			
			// aapt resource value: 0x7f04001a
			public const int textview_title = 2130968602;
			
			// aapt resource value: 0x7f040016
			public const int toastMessageTextView = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int toastTitleTextView = 2130968597;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int num_cols = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdministrationView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BillingInfo_ListElement = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BillingInfoView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int City_DropDownItemTemplate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int City_ItemTemplate = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ContactView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CustomToast = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DashboardView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int enum_dropdownitemtemplate = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int enum_item_tamplet = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int InternetUsageView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int InternetUseage_ListElement = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Menu_Fragment = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int menu_frame = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Menu_ListElement = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int News_ListElement = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int NewsView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int OrderView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ReportView = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SettingsView = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int slidingmenumain = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Speed_DropDownItemTemplate = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Speed_ItemTemplate = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int SplashScreen = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int UserInfoView = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int WebmailView = 2130903065;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int close_drawer = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int open_drawer = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090005
			public const int ButtonStyle_standard = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int EditTextStyle_standard = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int EditTextStyle_standard_multiline = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int MainLayoutBackground_Dashboard = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int TextViewStyle = 2131296257;
			
			// aapt resource value: 0x7f09000a
			public const int TextViewStyle_contact = 2131296266;
			
			// aapt resource value: 0x7f090006
			public const int TextViewStyle_standard_black_18 = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int TextViewStyle_title_black_22 = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int TextViewStyle_title_black_24 = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int TextViewStyle_title_white_22 = 2131296263;
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771984};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771987};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771985,
					2130771986};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] SlidingMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
